#!/bin/bash


#Have a virtualenv for different projects
cd ~/
cd ~/projects/"$1"
pyenv activate "$1"
. ~/.bashrc
tmux -2 new-session -d 'vim'
tmux new-window -n console
tmux new-window -n server 'python manage.py runserver'
tmux select-window -t :1
tmux -2 attach-session -d

